apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: task-kube
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/nginx
  persistentVolumeReclaimPolicy: Retain
